### ISSUE TITLE
Error producing name variations

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/rialto-etl#340]
```
[rialto@rialto-etl-prod current]$ time exe/transform call WebOfScience -i data/wos/wos_2010-01-01+2010-12-31.ndj > data/wos/wos_2010-01-01+2010-12-31.sparql
2019-01-10T12:43:10-08:00 [ WARN] 11753 : retrying connection (5 remaining) to https://rialto-resolver.sul.stanford.edu/organization?name=Stanford+University: (Faraday::ConnectionFailed) execution expired
2019-01-10T12:52:26-08:00 [ WARN] 11753 : retrying connection (5 remaining) to https://rialto-resolver.sul.stanford.edu/person?country=USA&first_name=Daisy&full_name=Rodriguez%2C+Daisy&last_name=Rodriguez&organization=Stanford+University: (Faraday::ConnectionFailed) execution expired
2019-01-10T13:06:28-08:00 [ WARN] 11753 : retrying connection (5 remaining) to https://rialto-resolver.sul.stanford.edu/organization?name=Stanford+Graduate+Fellowship: (Faraday::ConnectionFailed) execution expired
2019-01-10T13:25:10-08:00 [ WARN] 11753 : retrying connection (5 remaining) to https://rialto-resolver.sul.stanford.edu/organization?name=Stanford+University: (Faraday::ConnectionFailed) execution expired
Traceback (most recent call last):
        22: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
        21: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
        20: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
        19: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
        18: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
        17: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
        16: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/thread_pool.rb:123:in `block in maybe_in_thread_pool'
        15: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:554:in `block (3 levels) in process'
        14: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:429:in `map_to_context!'
        13: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:429:in `each'
        12: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:435:in `block in map_to_context!'
        11: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:476:in `handle_mapping_errors'
        10: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:436:in `block (2 levels) in map_to_context!'
         9: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer/step.rb:135:in `execute'
         8: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer/step.rb:135:in `each'
         7: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer/step.rb:138:in `block in execute'
         6: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:133:in `block (2 levels) in load_config_file'
         5: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:133:in `map'
         4: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:138:in `block (3 levels) in load_config_file'
         3: from /opt/app/rialto/rialto/releases/20190110192655/lib/rialto/etl/transformers/people.rb:95:in `resolve_or_construct_person'
         2: from /opt/app/rialto/rialto/releases/20190110192655/lib/rialto/etl/transformers/people.rb:74:in `construct_person'
         1: from /opt/app/rialto/rialto/releases/20190110192655/lib/rialto/etl/transformers/people.rb:53:in `name_variations_from_names'
/opt/app/rialto/rialto/releases/20190110192655/lib/rialto/etl/transformers/people/names.rb:61:in `name_variations_from_names': undefined method `[]' for true:TrueClass (NoMethodError)
```

**Comment by justinlittman** [comment]
It turns out some last names can be `""`.
