### ISSUE TITLE
rialto-etl cron is erroring out after update

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto-etl#409]
```
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/spec_set.rb:86:in `block in materialize': Could not find rake-12.3.3 in any of the sources (Bundler::GemNotFound)
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler.rb:149:in `setup'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from exe/extract:4:in `<main>'
```

**Comment by aaron-collier** [comment]
Resolved via redeploy after the 2.7.1 update.
